name: 🧪 Docs Test WorkFlow 📚

on:
  pull_request:
    branches: [main, develop]

# Restrict permissions by default
permissions:
  contents: read # Required for checkout
  checks: write # Required for test reporting

jobs:
  docs-build-test:
    name: Test docs build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: 📜 Setup Poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd # v3.0.1

      - name: 🏗️ Install dependencies
        run: |
          poetry install --with=docs

      - name: 🧪 Test Docs Build
        run: |
          poetry run mkdocs build --verbose
